[settings]
idiomatic_version_file_enable_tools = ["go", "node", "python"]

[tools]
go = "1.25.5"
node = "lts"
python = "3.13.11"
rust = "stable"
uv = "latest"

[env]
# Automatically create and activate Python venvs using 'uv'.
_.python.venv = { path = ".venv", create = true }
