[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
# NOTE: Update to "Super" on Linux.
mods = "Command"

[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 7500
multiplier = 3

[colors.cursor]
cursor = "#09bfdf"

[colors.vi_mode_cursor]
cursor = "#cda804"

# https://github.com/alacritty/alacritty-theme/blob/master/themes/remedy_dark.toml
# Default colors
[colors.primary]
# NOTE: `background` and `foreground` colors are custom
background = '#1d1f21'
foreground = '#c5c8c6'

dim_foreground    = '#685e4a'
bright_foreground = '#1c1508'

# Normal colors
[colors.normal]
black   = '#282a2e'
red     = '#a54242'
green   = '#8c9440'
yellow  = '#de935f'
blue    = '#5f819d'
magenta = '#85678f'
cyan    = '#5e8d87'
white   = '#707880'

# Bright colors
[colors.bright]
black   = '#373b41'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#8abeb7'
white   = '#c5c8c6'
