[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
# NOTE: Update to "Super" on Linux.
mods = "Command"

[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
history = 7500
multiplier = 3

[colors.cursor]
cursor = "#09bfdf"

[colors.vi_mode_cursor]
cursor = "#cda804"

# Colors (User Provided - Warmer)
[colors.primary]
background = '#232326'
foreground = '#a7aab0'

[colors.normal]
black   = '#101012'
red     = '#de5d68'
green   = '#8fb573'
yellow  = '#dbb671'
blue    = '#57a5e5'
magenta = '#bb70d2'
cyan    = '#51a8b3'
white   = '#a7aab0'

[colors.bright]
black   = '#5a5b5e'
red     = '#de5d68'
green   = '#8fb573'
yellow  = '#dbb671'
blue    = '#57a5e5'
magenta = '#bb70d2'
cyan    = '#51a8b3'
white   = '#a7aab0'
