---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespaces
        stages:
          - pre-commit
      - id: end-of-file-fixer
        name: Ensure file ends with a newline
        stages:
          - pre-commit
      - id: check-added-large-files
        name: Check for added large files
        stages:
          - pre-commit
  - repo: local
    hooks:
      - id: lint-commit-message
        name: Lint commit messages
        language: system
        entry: make lint-commit-message
        pass_filenames: false
        always_run: true
        stages:
          - commit-msg
      - id: lint-yaml
        name: Lint YAML files
        language: system
        types:
          - yaml
        pass_filenames: false
        entry: make lint-yaml
        stages:
          - pre-commit
      - id: lint-makefile
        name: Lint Makefile
        language: system
        types:
          - makefile
        pass_filenames: true
        entry: checkmake
        stages:
          - pre-commit
      - id: lint-fix-markdown
        name: Lint and fix Markdown files
        language: system
        types:
          - markdown
        pass_filenames: true
        entry: make lint-fix-markdown --
        stages:
          - pre-commit
      - id: actionlint
        name: Lint GitHub Actions
        language: system
        types:
          - yaml
        files: '^\.github/workflows/'
        pass_filenames: true
        entry: make lint-github-actions --
        stages:
          - pre-commit
      - id: lint-fix-shell-scripts
        name: Lint and fix Shell scripts
        language: system
        types:
          - shell
        exclude: "^(spec/|.vim/bundle/)"
        pass_filenames: true
        entry: make lint-fix-shell-scripts --
        stages:
          - pre-commit
      - id: lint-fix-lua
        name: Lint and fix Lua files
        language: system
        types:
          - lua
        pass_filenames: true
        entry: make lint-fix-lua --
        stages:
          - pre-commit
      - id: lint-ssh-config
        name: Lint SSH config
        language: system
        files: '^chezmoi/dot_ssh/config$'
        pass_filenames: false
        entry: make lint-ssh-config
        stages:
          - pre-commit
      - id: lint-gemini-settings
        name: Lint Gemini settings
        language: system
        files: '^chezmoi/dot_gemini/settings.json$'
        pass_filenames: false
        entry: make lint-gemini-settings
        stages:
          - pre-commit
