---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespaces
        stages:
          - pre-commit
      - id: end-of-file-fixer
        name: Ensure file ends with a newline
        stages:
          - pre-commit
      - id: check-added-large-files
        name: Check for added large files
        stages:
          - pre-commit
  - repo: local
    hooks:
      - id: lint-commit-message
        name: Lint commit messages
        language: system
        entry: make lint-commit-message
        pass_filenames: false
        always_run: true
        stages:
          - commit-msg
      - id: lint-makefile
        name: Lint Makefile
        language: system
        types:
          - makefile
        pass_filenames: true
        entry: checkmake
        stages:
          - pre-commit
      - id: lint-fix-markdown
        name: Lint and fix Markdown files
        language: system
        types:
          - markdown
        pass_filenames: true
        entry: make lint-fix-markdown --
        stages:
          - pre-commit
      - id: actionlint
        name: Lint GitHub Actions
        language: system
        types:
          - yaml
        files: '^\.github/workflows/'
        pass_filenames: true
        entry: make lint-github-actions --
        stages:
          - pre-commit
      - id: lint-vim
        name: Lint Vim scripts
        language: system
        files: '^\.vim/'
        pass_filenames: false
        entry: make lint-vim
        stages:
          - pre-commit
      - id: lint-shell-scripts
        name: Lint Shell scripts
        language: system
        types:
          - shell
        # TODO(skarzi): Remove ``.bashrc`` and ``.bash_aliases`` from exclusion
        # when they are compliant with ``shellcheck``.
        exclude: "^(spec/|.vim/bundle/|.bashrc|.bash_aliases)"
        pass_filenames: true
        entry: make lint-shell-scripts --
        stages:
          - pre-commit
      - id: lint-fix-lua
        name: Lint and fix Lua files
        language: system
        types:
          - lua
        pass_filenames: true
        entry: make lint-fix-lua --
        stages:
          - pre-commit
